# Generated by Django 3.0.6 on 2020-05-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200527_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='suffix',
        ),
    ]
