# Generated by Django 3.0.6 on 2020-05-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(default='Home', max_length=254),
            preserve_default=False,
        ),
    ]
